# Generated by Django 5.2.6 on 2025-09-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(db_column='NombreCompleto', max_length=100)),
                ('correo', models.CharField(db_column='Correo', max_length=100, unique=True)),
                ('contraseniaencriptada', models.CharField(db_column='ContraseniaEncriptada', max_length=255)),
            ],
            options={
                'db_table': 'dbo.Usuario',
                'managed': False,
            },
        ),
    ]
