# Generated by Django 5.2.6 on 2025-10-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_achievement_category_notification_savingsgoal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('savings', 'Ahorro')], max_length=10),
        ),
    ]
