# Generated by Django 5.2.6 on 2025-10-03 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('COP', 'Peso Colombiano (COP)'), ('USD', 'Dólar Americano (USD)'), ('EUR', 'Euro (EUR)')], default='COP', max_length=3)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('monthly_budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('savings_goal_reminder', models.BooleanField(default=True)),
                ('transaction_reminder', models.BooleanField(default=False)),
                ('language', models.CharField(default='es', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuario',
                'db_table': 'user_settings',
                'managed': True,
            },
        ),
    ]
