# Generated by Django 5.2.6 on 2025-10-03 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='DeletedAt', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='DeletedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to='accounts.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deletion_reason',
            field=models.TextField(blank=True, db_column='DeletionReason', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_deleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
    ]
