# Generated by Django 5.2.6 on 2025-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usuario_deleted_at_usuario_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='monthly_income',
            field=models.DecimalField(blank=True, db_column='MonthlyIncome', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='selected_savings_method',
            field=models.CharField(blank=True, choices=[('50-30-20', 'Método 50:30:20'), ('sobres', 'Método de Sobres'), ('automatico', 'Ahorro Automático'), ('1dolar', 'Ahorro del $1'), ('redondeo', 'Método del Redondeo')], db_column='SelectedSavingsMethod', max_length=50, null=True),
        ),
    ]
