# Generated by Django 5.2.6 on 2025-10-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_update_amount_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='current_balance',
            field=models.DecimalField(db_column='CurrentBalance', decimal_places=2, default=0, help_text='Saldo actual del usuario. Se actualiza al crear transacciones.', max_digits=15),
        ),
    ]
