# Generated by Django 5.2.6 on 2025-10-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usuario_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='savings_method_selected_at',
            field=models.DateTimeField(blank=True, db_column='SavingsMethodSelectedAt', help_text='Fecha en que el usuario seleccionó su método de ahorro', null=True),
        ),
    ]
